### ISSUE TITLE
Annotations server not starting in current docker-compose installation

### ISSUE THREAD

**Issue by doingandlearning** [digirati-co-uk/madoc-platform#108]
What I did
- I ran `madoc init` and `madoc start`
- I navigated to localhost:8889

What did I expect
- To see the annotation server 

What did I see
- I saw the Tomcat successful installation page `If you're seeing this, you've successfully installed Tomcat. Congratulations!`

The other components have set-up and configured properly but the annotation server doesn't seem to have kicked in. I haven't changed any of the .env files, the documentation suggests a different port but I can see from the docker-compose file that it should be on 8889. 

I'm not sure how to move this one forward.

**Comment by stephenwf** [comment]
Hi @doingandlearning, the annotation server should be working, there is no root to the annotation server, it does follow the [W3C Annotation Protocol](https://www.w3.org/TR/annotation-protocol/) so you can test that it is working by posting a new container:
```
curl -X "POST" "http://localhost:8889/annotation/w3c/" \
     -H 'Content-Type: application/ld+json; profile="http://www.w3.org/ns/anno.jsonld"' \
     -d $'{
  "label": "Content source",
  "type": "AnnotationCollection",
  "@context": [
    "http://www.w3.org/ns/anno.jsonld",
    "http://www.w3.org/ns/ldp.jsonld"
  ],
  "label": "testing label"
}'
```

That will return something like:
```
{
  "@context" : [ "http://www.w3.org/ns/anno.jsonld", "http://www.w3.org/ns/ldp.jsonld" ],
  "id" : "http://localhost:8889/annotation/w3c/2da77ed9-bcfa-4700-b1b1-c9030b756b5f/",
  "type" : "AnnotationCollection",
  "label" : "testing label",
  "first" : {
    "type" : "AnnotationPage",
    "as:items" : {
      "@list" : [ ]
    },
    "partOf" : "http://localhost:8889/annotation/w3c/2da77ed9-bcfa-4700-b1b1-c9030b756b5f/",
    "startIndex" : 0
  },
  "last" : "http://localhost:8889/annotation/w3c/2da77ed9-bcfa-4700-b1b1-c9030b756b5f/?page=0&desc=1",
  "total" : 0
}
```

The `@id` that is returned can be POST-ed against to create an annotation inside of that container.

Madoc will do that automatically when you start annotating images, creating a new container for each canvas.

**Comment by doingandlearning** [comment]
As you say - works fine - thanks for getting back to me so quickly!
