### ISSUE TITLE
Mark as complete button

### ISSUE THREAD

**Issue by NLW-paulm** [digirati-co-uk/madoc-platform#111]
The mark as complete dialog popup contains a dark grey button with black text to 'Mark as Complete'. Can this be changed to be readable?

(We are aware this is changeable via CSS in the theme footer, but feel its a platform issue, rather than having to do a 'fix' on each site we use.)

TAGS: Bug, NLW

**Comment by NLW-paulm** [comment]
This is still black text on grey button unfortunately.

**Comment by stephenwf** [comment]
I had the same issue, but it worked correctly after clearing the cache on that page (or hard-refreshing).

<img width="605" alt="Screenshot 2019-10-07 at 15 00 31" src="https://user-images.githubusercontent.com/8266711/66318472-46069e00-e913-11e9-8785-413496e296b4.png">

**Comment by NLW-paulm** [comment]
Weird, I was on a different machine, but clearing the cache has fixed it :-)

**Comment by stephenwf** [comment]
that is strange!
