### ISSUE TITLE
10 annotation limit

### ISSUE THREAD

**Issue by NLW-paulm** [digirati-co-uk/madoc-platform#112]
The limit of 10 annotations per page has been fixed and tested on the new site, so we know its working fine. However canvases that definitely had more than 10 annotations on the 'live' site are still only showing 10 annotations on the new site. 

So it's possible during import the 10 limit, prevented all the annotations being brought across.

This item should have more than 10 annos
https://omeka.nlw.digtest.co.uk/s/livingstone/collections/view/16520/1525/9543

TAGS: NLW, API,

**Comment by stephenwf** [comment]
Hi @NLW-paulm I assessed creating a patch for the old omeka modules, but its likely to be time consuming as it's a stale dependency. The issue has been fixed in the new Madoc Elucidate proxy module, so will not appear again when we migrate the Elucidate and domains over.
