### ISSUE TITLE
Items marked as complete - cant edit

### ISSUE THREAD

**Issue by NLW-paulm** [digirati-co-uk/madoc-platform#115]
On the live site we can un-mark completed items for editing. But this is not possible on the new site on either the live data or mutable. Items that can be un-marked on the live site are just locked on the new site. 

Also are annotations still in draft status on the new platform?

Tags: Bug, NLW.

**Comment by stephenwf** [comment]
Yes, they are still in the draft status on the new platform. I've fixed the bug relating to this in #121
