### ISSUE TITLE
GLE Date picker

### ISSUE THREAD

**Issue by NLW-paulm** [digirati-co-uk/madoc-platform#116]
On GLE the date picker (Whole Photograph -> What is exact date) defaults to 2019, but as these projects are all based on old photos/documents is it possible to preset the date in the datepicker as part of the content model?

Tags:NLW, Feature request/enhancement

**Comment by mattmcgrattan** [comment]
This can be set by setting:

`uiInputDefaultValue` in the capture model, e.g. to `1965-01-01T14:50:35+00:00`.

This should (for now) be done post import, as there's an issue with the parsing of the field in the JSON generator code. 

@NLW-paulm

**Comment by mattmcgrattan** [comment]
Actually, @NLW-paulm ignore that, I've updated the code in the nlw-madoc-models repo to use a regex to check it's not a NNNN-NN-NNTNN:NN:NN+NN:NN formatted string.

N.B. it checks for that specific format, so you need the entire date time as given above.
