### ISSUE TITLE
Date Taken import issue

### ISSUE THREAD

**Issue by NLW-paulm** [digirati-co-uk/madoc-platform#117]
Capture model - ON GLE Whole Photograph - what date was this taken. 

Each year is listed as its own selection except for 1962-1978 which is one line/selection, these should each be listed as individual years. 

import issue. 

Yes, this can be fixed in Admin, but being noted here for next import otherwise we will be in same situation and maybe a bug in importer that will affect other lists/dropdowns.

Tags NLW, Bug, API

**Comment by mattmcgrattan** [comment]
This has now been fixed.

There was a bug in the code that generates the JSON from an exported CSV. The JSON was producing a string rather than a list. So I added some (crude) string handling to convert it back to a proper list again.

@NLW-paulm
