### ISSUE TITLE
Users cant use site once registered

### ISSUE THREAD

**Issue by NLW-paulm** [digirati-co-uk/madoc-platform#129]
When a user registers it sets the user role to 'transcriber' however the system is expecting 'Transcriber' (with a capital T). Because the user is then logged in, any page it tries to access is shown an error

`/srv/omeka/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php
/srv/omeka/index.php
     Zend\Permissions\Acl\Exception\InvalidArgumentException: Role 'transcriber' not found in /srv/omeka/vendor/zendframework/zend-permissions-acl/src/Role/Registry.php:106
Stack trace:
#0 /srv/omeka/vendor/zendframework/zend-permissions-acl/src/Acl.php(728): Zend\Permissions\Acl\Role\Registry->get(Object(Omeka\Entity\User))
#1 /srv/omeka/application/src/Permissions/Acl.php(87): Zend\Permissions\Acl\Acl->isAllowed(Object(Omeka\Entity\User), 'PublicUser\\Cont...', 'create-password')
#2 /srv/omeka/application/src/Mvc/MvcListeners.php(429): Omeka\Permissions\Acl->userIsAllowed('PublicUser\\Cont...', 'create-password')
#3 /srv/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Omeka\Mvc\MvcListeners->authorizeUserAgainstController(Object(Zend\Mvc\MvcEvent))
#4 /srv/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /srv/omeka/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#6 /srv/omeka/index.php(21): Zend\Mvc\Application->run()
#7 {main} `

We have created a number of users to test this and all seem to be created as transcriber, regardless of which site is used. We have left one user with this role so it can be viewed/investigated. This seems to have been introduced in the last week or so.

User role is set to 'Transcriber' in the site settings.
Tags #bug, #nlw

**Comment by stephenwf** [comment]
Fixed by #130
