### ISSUE TITLE
Required repositories are private

### ISSUE THREAD

**Issue by bencomp** [digirati-co-uk/madoc-platform#2]
When following the [Madoc installation guide](https://madoc.netlify.com/getting-started/installation/), during `./bin/madoc init` I get error messages that repositories can not be found. Judging from <https://github.com/digirati-co-uk?utf8=%E2%9C%93&q=omeka&type=&language=>, only three repositories with 'Omeka' in their name are public. Is that on purpose? Is this platform and documentation only meant for Digirati installations?

**Comment by stephenwf** [comment]
Hi @bencomp the repositories themselves are [bare repositories](https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server) so they are a way of linking our internal repositories back to their original source control. When the repositories are cloned, no files are added so its not a required step. I will change the `init` script to not run this step though, as its obviously not expected!

**Comment by stephenwf** [comment]
In the mean time, you can use `./bin/madoc server-init` to get the absolute requirements (Omeka-S and a shared library)

**Comment by bencomp** [comment]
@stephenwf thanks for the info. After my failed first attempt I had to delete the whole repository and clone again to be able to run the `server-init` command succesfully.

Now I'm stuck on the `/login` page with only the `admin@example.org` user name that I found in the SQL files, but no password that goes with it. Would you like me to open another issue to ask for it?

**Comment by stephenwf** [comment]
Ah sorry, yes the initial details are:
```
email: admin@example.org
password: Testpass123_
```
I will add that to the readme again
