### ISSUE TITLE
Interact with this document

### ISSUE THREAD

**Issue by NLW-paulm** [digirati-co-uk/madoc-platform#60]
The options under interact with this document, Mark as Complete, Bookmark, Flag are missing for some users.

This is an odd one, because the first time I tested, these appeared, last week when the volunteers reported it I also did not get the menu when logging in, but today it appears to be back. 

Im leaving this bug here until I can capture more information from the volunteers, as its seems to come and go and maybe in specific circumstances only.

**Comment by NLW-paulm** [comment]
Im going to close this, as it appears to have been un-reproducable recently.

**Comment by stephenwf** [comment]
This may have been related to #115 and fixed recently (although not deployed)
