### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by dnoneill** [digirati-co-uk/madoc-platform#643]
Hi,
Quick question. Are the annotations viewable in a W3C web annotation framework. Either through export or URL or both?

Thanks!

**Comment by stephenwf** [comment]
It depends on the type of annotation. You can create complex structured annotations that are not easy to express with W3C, however simple annotations can be extracted via a URL:
https://docs.madoc.io/api-guide/iiif-derived-api/exporting-annotations

**Comment by dnoneill** [comment]
@stephenwf Thank you!
